# -*- coding: utf-8 -*-
"""Rayed_Nayab_Intro_to_ML_HW3_801411277

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aO8H3Aaow9SODx0XjhcYOOCxPWA4LoTe
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = 'https://raw.githubusercontent.com/HamedTabkhi/Intro-to-ML/main/Dataset/Cancer.csv'
df = pd.read_csv(url)
print(df.head())

"""### Step 1: Preprocess the Data"""

# Clean columns and encode target
df_cleaned = df.drop(columns=['id', 'Unnamed: 32'], errors='ignore')
df_cleaned['diagnosis'] = df_cleaned['diagnosis'].map({'M': 1, 'B': 0})

# Split features and target
X = df_cleaned.drop(columns=['diagnosis'])
y = df_cleaned['diagnosis']

display(df_cleaned.head())

"""### Step 2: Split and Scale the Dataset"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split data (80% training, 20% evaluation)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Training set shape: {X_train_scaled.shape}")
print(f"Evaluation set shape: {X_test_scaled.shape}")

"""### Step 3: Train and Evaluate Logistic Regression Classifier

"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Initialize and train the model
model = LogisticRegression(random_state=42)
model.fit(X_train_scaled, y_train)

# Predict on the evaluation set
y_pred = model.predict(X_test_scaled)

# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

"""### Step 4: The Confusion Matrix"""

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot the heatmap
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Benign (0)', 'Malignant (1)'],
            yticklabels=['Benign (0)', 'Malignant (1)'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix Heatmap')
plt.show()

"""### Step 5: Logistic Regression"""

# Initialize and train the Logistic Regression model using the existing scaled data
model = LogisticRegression(random_state=42)
model.fit(X_train_scaled, y_train)

# Make predictions on the existing evaluation set
y_pred = model.predict(X_test_scaled)

# Display classification metrics
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Calculate and plot the confusion matrix heatmap
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Benign (0)', 'Malignant (1)'],
            yticklabels=['Benign (0)', 'Malignant (1)'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix Heatmap')
plt.show()

"""### Step 6: Logistic Regression with Weight Penalty (Regularization)"""

# Train a Logistic Regression model with a strong L2 weight penalty (C=0.1)
penalty_model_l2 = LogisticRegression(penalty='l2', C=0.1, random_state=42)
penalty_model_l2.fit(X_train_scaled, y_train)
y_pred_l2 = penalty_model_l2.predict(X_test_scaled)

# Train a Logistic Regression model with an L1 weight penalty (using liblinear solver)
penalty_model_l1 = LogisticRegression(penalty='l1', solver='liblinear', C=0.1, random_state=42)
penalty_model_l1.fit(X_train_scaled, y_train)
y_pred_l1 = penalty_model_l1.predict(X_test_scaled)

# Display classification metrics
print("=== L2 Penalty (C=0.1) ===")
print("Accuracy Score:", accuracy_score(y_test, y_pred_l2))
print(classification_report(y_test, y_pred_l2))

print("\n=== L1 Penalty (C=0.1) ===")
print("Accuracy Score:", accuracy_score(y_test, y_pred_l1))
print(classification_report(y_test, y_pred_l1))

# Plot side-by-side Confusion Matrices
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

cm_l2 = confusion_matrix(y_test, y_pred_l2)
sns.heatmap(cm_l2, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['Benign (0)', 'Malignant (1)'],
            yticklabels=['Benign (0)', 'Malignant (1)'])
axes[0].set_title('L2 Penalty (C=0.1) Confusion Matrix')
axes[0].set_xlabel('Predicted')
axes[0].set_ylabel('True')

cm_l1 = confusion_matrix(y_test, y_pred_l1)
sns.heatmap(cm_l1, annot=True, fmt='d', cmap='Oranges', ax=axes[1],
            xticklabels=['Benign (0)', 'Malignant (1)'],
            yticklabels=['Benign (0)', 'Malignant (1)'])
axes[1].set_title('L1 Penalty (C=0.1) Confusion Matrix')
axes[1].set_xlabel('Predicted')
axes[1].set_ylabel('True')

plt.tight_layout()
plt.show()