# -*- coding: utf-8 -*-
"""Intro_to_ML_HW4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdqwWYIIzYxqwFkmxUaufqADF5nK239I
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

"""### Problem 1: SVM Classifier Using the Cancer Dataset"""

url = 'https://raw.githubusercontent.com/HamedTabkhi/Intro-to-ML/main/Dataset/Cancer.csv'
df = pd.read_csv(url)
print(df.head())

"""### Step 1: Preprocess the Data
We will drop unnecessary columns (like `id` and `Unnamed: 32`), map the categorical target variable `diagnosis` ('M' to 1, 'B' to 0), and scale the feature variables using `StandardScaler` to optimize SVM performance.
"""

# 1. Clean dataset
# Drop columns that are not features
df_cleaned = df.drop(columns=['id', 'Unnamed: 32'], errors='ignore')

# Map diagnosis to binary target: M (malignant) = 1, B (benign) = 0
df_cleaned['diagnosis'] = df_cleaned['diagnosis'].map({'M': 1, 'B': 0})

# Split features and target
X = df_cleaned.drop(columns=['diagnosis'])
y = df_cleaned['diagnosis']

# Split dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Training set shape: {X_train_scaled.shape}")
print(f"Testing set shape: {X_test_scaled.shape}")

"""### Step 2: Explore Different Kernels & Evaluate Models
We will train SVM classifiers using different kernel tricks: `linear`, `rbf` (Radial Basis Function), and `poly` (Polynomial). For each, we will calculate accuracy, precision, and recall.
"""

kernels = ['linear', 'rbf', 'poly']
results = {}

for kernel in kernels:
    # Train SVM classifier
    clf = SVC(kernel=kernel, random_state=42)
    clf.fit(X_train_scaled, y_train)

    # Predict
    y_pred = clf.predict(X_test_scaled)

    # Compute metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)

    results[kernel] = {
        'Accuracy': acc,
        'Precision': prec,
        'Recall': rec
    }

# Convert results to DataFrame for easier plotting
df_results = pd.DataFrame(results).T
display(df_results)

"""### Step 3: Plot and Compare the Results
We will visualize the performance metrics (Accuracy, Precision, and Recall) across different SVM kernels using a bar chart.
"""

# Reshape the dataframe for plotting
df_plot = df_results.reset_index().rename(columns={'index': 'Kernel'})
df_melted = pd.melt(df_plot, id_vars=['Kernel'], value_vars=['Accuracy', 'Precision', 'Recall'],
                    var_name='Metric', value_name='Score')

# Generate the comparison plot
plt.figure(figsize=(10, 6))
sns.barplot(data=df_melted, x='Kernel', y='Score', hue='Metric', palette='viridis')
plt.title('Comparison of SVM Kernels on Cancer Dataset')
plt.xlabel('SVM Kernel')
plt.ylabel('Score')
plt.ylim(0.85, 1.01)  # Focus on the high-performance range
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

"""### Problem 2: SVR Regression Model With the Housing Dataset"""

url = 'https://raw.githubusercontent.com/HamedTabkhi/Intro-to-ML/main/Dataset/Housing.csv'
df = pd.read_csv(url)
print(df.head())

"""### Step 1: Preprocess the Housing Dataset
We will map the categorical binary columns (`yes`/`no`) to `1`/`0`, separate features and target, scale both features and target using `StandardScaler` (since SVR is highly sensitive to feature scaling), and split the dataset into train and test sets.
"""

from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

# Create a copy of the housing dataframe to avoid modifying original variables
housing_df = df.copy()

# List of binary features to map
binary_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
for col in binary_cols:
    housing_df[col] = housing_df[col].map({'yes': 1, 'no': 0})

# Define our features (X) and target (y)
features = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea']
X_house = housing_df[features]
y_house = housing_df['price']

# Split into training and testing sets
X_train_h, X_test_h, y_train_h, y_test_h = train_test_split(X_house, y_house, test_size=0.2, random_state=42)

# Standardize both features and target for SVR optimization
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train_h_scaled = scaler_X.fit_transform(X_train_h)
X_test_h_scaled = scaler_X.transform(X_test_h)

# SVR requires the target y to be a 2D array for fit_transform
y_train_h_scaled = scaler_y.fit_transform(y_train_h.values.reshape(-1, 1)).ravel()
y_test_h_scaled = scaler_y.transform(y_test_h.values.reshape(-1, 1)).ravel()

print("Preprocessed housing features shape:", X_train_h_scaled.shape)

"""### Step 2: Train SVR with Linear, RBF, and Poly Kernels & Plot Results
We will train the SVR models, inverse-transform the predictions back to the original price scale, and visualize the predicted vs. actual prices for each kernel.
"""

kernels = ['linear', 'rbf', 'poly']
predictions = {}
metrics = {}

for kernel in kernels:
    # Train SVR
    svr = SVR(kernel=kernel, C=1.0, epsilon=0.1)
    svr.fit(X_train_h_scaled, y_train_h_scaled)

    # Predict
    y_pred_scaled = svr.predict(X_test_h_scaled)

    # Inverse scale predictions back to actual currency scale
    y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()
    predictions[kernel] = y_pred

    # Calculate metrics
    r2 = r2_score(y_test_h, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test_h, y_pred))
    metrics[kernel] = {'R2 Score': r2, 'RMSE': rmse}

# Display the evaluation summary
df_metrics = pd.DataFrame(metrics).T
display(df_metrics)

"""### Step 3: Tuning the Parameters for Poly and RBF Kernels
We will use `GridSearchCV` to sweep across multiple parameters (such as `C`, `gamma`, and `degree`) to improve the accuracy of our non-linear kernels before visualizing our final results.
"""

from sklearn.model_selection import GridSearchCV

# --- 1. Optimize RBF Kernel ---
print("Tuning RBF Kernel...")
rbf_param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': ['scale', 'auto', 0.01, 0.1, 1]
}
grid_rbf = GridSearchCV(SVR(kernel='rbf'), rbf_param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_rbf.fit(X_train_h_scaled, y_train_h_scaled)

best_rbf_svr = grid_rbf.best_estimator_
print(f"Best RBF Params: {grid_rbf.best_params_}")

# --- 2. Optimize Polynomial Kernel ---
print("\nTuning Polynomial Kernel...")
poly_param_grid = {
    'C': [0.1, 1, 10],
    'degree': [2, 3, 4],
    'coef0': [0.0, 1.0, 2.0]
}
grid_poly = GridSearchCV(SVR(kernel='poly'), poly_param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_poly.fit(X_train_h_scaled, y_train_h_scaled)

best_poly_svr = grid_poly.best_estimator_
print(f"Best Poly Params: {grid_poly.best_params_}")

# Predict and evaluate with optimized models
y_pred_rbf_opt_scaled = best_rbf_svr.predict(X_test_h_scaled)
y_pred_rbf_opt = scaler_y.inverse_transform(y_pred_rbf_opt_scaled.reshape(-1, 1)).ravel()

y_pred_poly_opt_scaled = best_poly_svr.predict(X_test_h_scaled)
y_pred_poly_opt = scaler_y.inverse_transform(y_pred_poly_opt_scaled.reshape(-1, 1)).ravel()

# Compute new metrics
r2_rbf_opt = r2_score(y_test_h, y_pred_rbf_opt)
r2_poly_opt = r2_score(y_test_h, y_pred_poly_opt)

print(f"Original RBF R²: {metrics['rbf']['R2 Score']:.4f}  ==>  Optimized RBF R²: {r2_rbf_opt:.4f}")
print(f"Original Poly R²: {metrics['poly']['R2 Score']:.4f}  ==>  Optimized Poly R²: {r2_poly_opt:.4f}")

"""### Step 4: Combined SVR Prediction Lines vs. Actual Price Dots
Now, we plot the sorted actual prices as individual dots and compare the predictions from our original linear kernel and our newly optimized non-linear SVR kernels.
"""

# Sort actual prices to ensure continuous trend lines without zigzags
sort_idx = np.argsort(y_test_h.values)
y_test_sorted = y_test_h.values[sort_idx]

plt.figure(figsize=(12, 8))

# Plot actual prices as dots
plt.scatter(range(len(y_test_sorted)), y_test_sorted, color='black', alpha=0.7, s=30, label='Actual Price (Dots)', zorder=2)

# Define colors
colors = {'linear': '#1f77b4', 'rbf': '#ff7f0e', 'poly': '#2ca02c'}

# Plot original linear and optimized RBF & Poly predictions
plt.plot(range(len(y_test_sorted)), predictions['linear'][sort_idx], color=colors['linear'], lw=2.5,
         label=f'LINEAR Kernel (R²: {metrics["linear"]["R2 Score"]:.3f})', zorder=3)
plt.plot(range(len(y_test_sorted)), y_pred_rbf_opt[sort_idx], color=colors['rbf'], lw=2.5,
         label=f'Optimized RBF Kernel (R²: {r2_rbf_opt:.3f})', zorder=3)
plt.plot(range(len(y_test_sorted)), y_pred_poly_opt[sort_idx], color=colors['poly'], lw=2.5,
         label=f'Optimized POLY Kernel (R²: {r2_poly_opt:.3f})', zorder=3)

plt.title('Optimized SVR Kernel Prediction Lines vs. Actual Price Dots', fontsize=14)
plt.xlabel('Sorted Sample Index', fontsize=12)
plt.ylabel('Housing Price', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(fontsize=11)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 8))

# Plot the ratio (predicted / actual) vs actual price for original linear and optimized kernels
ratio_linear = predictions['linear'] / y_test_h.values
ratio_rbf = y_pred_rbf_opt / y_test_h.values
ratio_poly = y_pred_poly_opt / y_test_h.values

plt.scatter(y_test_h.values, ratio_linear, color=colors['linear'], alpha=0.6, edgecolors='k', s=40,
            label=f'LINEAR Kernel (R²: {metrics["linear"]["R2 Score"]:.3f})')
plt.scatter(y_test_h.values, ratio_rbf, color=colors['rbf'], alpha=0.6, edgecolors='k', s=40,
            label=f'Optimized RBF Kernel (R²: {r2_rbf_opt:.3f})')
plt.scatter(y_test_h.values, ratio_poly, color=colors['poly'], alpha=0.6, edgecolors='k', s=40,
            label=f'Optimized POLY Kernel (R²: {r2_poly_opt:.3f})')

# A perfect prediction means Predicted / Actual = 1.0
plt.axhline(y=1.0, color='r', linestyle='--', lw=2, label='Perfect Prediction (Ratio = 1.0)')

plt.title('Ratio of Optimized Predictions to Actual Housing Prices', fontsize=14)
plt.xlabel('Actual Price', fontsize=12)
plt.ylabel('Prediction Ratio (Predicted / Actual)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(fontsize=11)
plt.tight_layout()
plt.show()