# -*- coding: utf-8 -*-
"""Intro_to_ML_HW2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yl8ylm9diUQB84NNTZAt90NTAr8bB3mC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

url = 'https://raw.githubusercontent.com/HamedTabkhi/Intro-to-ML/main/Dataset/Housing.csv'
df = pd.read_csv(url)
print(df.head())

for col in ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']:
    df[col] = df[col].map({'yes': 1, 'no': 0})

df['furnishingstatus'] = df['furnishingstatus'].map({
    'furnished': 2,
    'semi-furnished': 1,
    'unfurnished': 0
})

print("DataFrame after converting categorical features:")
print(df.head())

y = df.values[:, 0]
raw_area = df.values[:, 1]
raw_bedrooms = df.values[:, 2]
raw_bathrooms = df.values[:, 3]
raw_stories = df.values[:, 4]
raw_mainroad = df.values[:, 5]
raw_guestroom = df.values[:, 6]
raw_basement = df.values[:, 7]
raw_hotwater = df.values[:, 8]
raw_airconditioning = df.values[:, 9]
raw_parking = df.values[:, 10]
raw_prefarea = df.values[:, 11]
raw_furnishingstatus = df.values[:, 12]

m = df.shape[0]

temp = np.ones((m, 1))

X_area = np.hstack((temp, raw_area.reshape(m,1)))
X_bedrooms = np.hstack((temp, raw_bedrooms.reshape(m,1)))
X_bathrooms = np.hstack((temp, raw_bathrooms.reshape(m,1)))
X_stories = np.hstack((temp, raw_stories.reshape(m,1)))
X_mainroad = np.hstack((temp, raw_mainroad.reshape(m,1)))
X_guestroom = np.hstack((temp, raw_guestroom.reshape(m,1)))
X_basement = np.hstack((temp, raw_basement.reshape(m,1)))
X_hotwater = np.hstack((temp, raw_hotwater.reshape(m,1)))
X_airconditioning = np.hstack((temp, raw_airconditioning.reshape(m,1)))
X_parking = np.hstack((temp, raw_parking.reshape(m,1)))
X_prefarea = np.hstack((temp, raw_prefarea.reshape(m,1)))
X_furnishingstatus = np.hstack((temp, raw_furnishingstatus.reshape(m,1)))

theta = np.zeros(2) # Initial theta for single feature cost calculation, not used in multi-feature training below

def compute_cost(X, Y, theta):
    predictions = X.dot(theta)
    errors = np.subtract(predictions, Y)
    sqrErrors = np.square(errors)
    # Use X.shape[0] for m to be general for train/validation sets
    J = (1 / (2 * X.shape[0])) * np.sum(sqrErrors)
    return J

# The following individual cost computations will now use X.shape[0] within compute_cost
areacost = compute_cost(X_area, y, theta)
bedroomscost = compute_cost(X_bedrooms, y, theta)
bathroomscost = compute_cost(X_bathrooms, y, theta)
storiescost = compute_cost(X_stories, y, theta)
parkingcost = compute_cost(X_parking, y, theta)

def compute_cost(X, Y, theta, lambda_param=0):
    predictions = X.dot(theta)
    errors = np.subtract(predictions, Y)
    sqrErrors = np.square(errors)
    # Regularization term for L2 (Ridge) regression, excludes theta[0] (intercept)
    regularization_term = (lambda_param / (2 * X.shape[0])) * np.sum(np.square(theta[1:]))
    J = (1 / (2 * X.shape[0])) * np.sum(sqrErrors) + regularization_term
    return J

def gradient_descent(X, y, theta_initial, alpha, iterations, lambda_param=0):
    theta = theta_initial.copy() # Use a copy to avoid modifying initial_theta directly
    cost_history = np.zeros(iterations)

    m_local = X.shape[0] # Use X.shape[0] for m to be general for train/validation sets

    for i in range(iterations):
        predictions = X.dot(theta)
        errors = np.subtract(predictions, y)

        # Gradient for theta[0] (intercept) - no regularization
        gradient_theta0 = (alpha / m_local) * np.sum(errors)

        # Gradient for theta[1:] (other features) - with L2 regularization
        gradient_others = (alpha / m_local) * X[:, 1:].transpose().dot(errors) + (alpha * lambda_param / m_local) * theta[1:]

        # Update theta
        theta[0] -= gradient_theta0
        theta[1:] -= gradient_others

        cost_history[i] = compute_cost(X, y, theta, lambda_param) # compute_cost now uses X.shape[0]

    return theta, cost_history

iterations = 2000
alpha = 0.01

areatheta, areacost_history = gradient_descent(X_area, y, np.zeros(2), alpha, iterations)
bedroomstheta, bedroomscost_history = gradient_descent(X_bedrooms, y, np.zeros(2), alpha, iterations)
bathroomstheta, bathroomscost_history = gradient_descent(X_bathrooms, y, np.zeros(2), alpha, iterations)
storiestheta, storiescost_history = gradient_descent(X_stories, y, np.zeros(2), alpha, iterations)
parkingtheta, parkingcost_history = gradient_descent(X_parking, y, np.zeros(2), alpha, iterations)

print("Area Theta:", areatheta)
print("Bedrooms Theta:", bedroomstheta)
print("Bathrooms Theta:", bathroomstheta)
print("Stories Theta:", storiestheta)
print("Parking Theta:", parkingtheta)
print("Area Cost History (last 5):"), print(areacost_history[-5:])
print("Bedrooms Cost History (last 5):"), print(bedroomscost_history[-5:])
print("Bathrooms Cost History (last 5):"), print(bathroomscost_history[-5:])
print("Stories Cost History (last 5):"), print(storiescost_history[-5:])
print("Parking Cost History (last 5):"), print(parkingcost_history[-5:])

from sklearn.model_selection import train_test_split

# Combine the scaled features into a single X matrix
# Make sure to include the intercept term in the first column
X = np.hstack((
    X_area[:, 0].reshape(-1, 1), # Intercept (all ones) - only need it once
    X_area[:, 1].reshape(-1, 1),
    X_bedrooms[:, 1].reshape(-1, 1),
    X_bathrooms[:, 1].reshape(-1, 1),
    X_stories[:, 1].reshape(-1, 1),
    X_parking[:, 1].reshape(-1, 1)
))

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize theta for the combined features
theta_initial_multi = np.zeros(X_train.shape[1])

print("Shape of combined X:", X.shape)
print("Shape of X_train:", X_train.shape)
print("Shape of X_val:", X_val.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_val:", y_val.shape)
print("Initial Theta for combined features:", theta_initial_multi)

# Define the learning rate and iterations for this specific training
alpha_multi = 0.01
iterations_multi = 2000 # Using the same iterations as before

# Train the model with combined features (not 'all' features)
theta_trained_multi, training_losses_multi_history = gradient_descent(X_train, y_train, theta_initial_multi, alpha_multi, iterations_multi)

# Calculate the final validation cost
validation_loss_multi = compute_cost(X_val, y_val, theta_trained_multi)

print(f"Final Training Loss (Combined Features): {training_losses_multi_history[-1]:.4f}")
print(f"Final Validation Loss (Combined Features): {validation_loss_multi:.4f}")

plt.figure(figsize=(12, 6))

# Plot training loss
plt.plot(range(iterations_multi), training_losses_multi_history, label=f'Training Loss (Combined Features, LR={alpha_multi:.4f})', color='blue')

# Plot validation loss (as a horizontal line since it's a single value)
plt.axhline(y=validation_loss_multi, color='red', linestyle='--', label=f'Validation Loss (Combined Features, LR={alpha_multi:.4f}) = {validation_loss_multi:.4f}')

plt.title('Training and Validation Loss over Iterations (Combined Features)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

from sklearn.model_selection import train_test_split

# Combine all scaled features into a single X matrix
# Make sure to include the intercept term only once
X_all = np.hstack((
    X_area[:, 0].reshape(-1, 1), # Intercept (all ones)
    X_area[:, 1].reshape(-1, 1),
    X_bedrooms[:, 1].reshape(-1, 1),
    X_bathrooms[:, 1].reshape(-1, 1),
    X_stories[:, 1].reshape(-1, 1),
    X_parking[:, 1].reshape(-1, 1),
    X_mainroad[:, 1].reshape(-1, 1),
    X_guestroom[:, 1].reshape(-1, 1),
    X_basement[:, 1].reshape(-1, 1),
    X_hotwater[:, 1].reshape(-1, 1),
    X_airconditioning[:, 1].reshape(-1, 1),
    X_prefarea[:, 1].reshape(-1, 1),
    X_furnishingstatus[:, 1].reshape(-1, 1)
))

# Split the data into training and validation sets
X_train_all, X_val_all, y_train_all, y_val_all = train_test_split(X_all, y, test_size=0.2, random_state=42)

# Initialize theta for the combined features
theta_initial_all = np.zeros(X_train_all.shape[1])

print("Shape of combined X_all:", X_all.shape)
print("Shape of X_train_all:", X_train_all.shape)
print("Shape of X_val_all:", X_val_all.shape)
print("Shape of y_train_all:", y_train_all.shape)
print("Shape of y_val_all:", y_val_all.shape)
print("Initial Theta for all combined features:", theta_initial_all)

# Define the learning rate and iterations for this specific training
alpha_multi = 0.01
iterations_multi = 2000 # Using the same iterations as before

# Train the model with all features
theta_trained_multi_all, training_losses_multi_history_all = gradient_descent(X_train_all, y_train_all, theta_initial_all, alpha_multi, iterations_multi)

# Calculate the final validation cost
validation_loss_multi_all = compute_cost(X_val_all, y_val_all, theta_trained_multi_all)

print(f"Final Training Loss (All Features): {training_losses_multi_history_all[-1]:.4f}")
print(f"Final Validation Loss (All Features): {validation_loss_multi_all:.4f}")

plt.figure(figsize=(12, 6))

# Plot training loss
plt.plot(range(iterations_multi), training_losses_multi_history_all, label=f'Training Loss (Combined Features, LR={alpha_multi:.4f})', color='blue')

# Plot validation loss (as a horizontal line since it's a single value)
plt.axhline(y=validation_loss_multi_all, color='red', linestyle='--', label=f'Validation Loss (Combined Features, LR={alpha_multi:.4f}) = {validation_loss_multi:.4f}')

plt.title('Training and Validation Loss over Iterations (Combined Features)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### Data Normalization for Subset of Features (Target Unnormalized)

Let's apply Min-Max Normalization to the subset of features (`X`) while keeping the target variable `y` in its original scale. This will allow us to observe the model's performance with a different scaling approach.
"""

from sklearn.preprocessing import MinMaxScaler

# Initialize MinMaxScaler for the subset of features (X)
scaler_X_subset_norm = MinMaxScaler()
X_subset_normalized = scaler_X_subset_norm.fit_transform(X)

# Split the normalized subset data and original y into training and validation sets
X_train_subset_normalized, X_val_subset_normalized, y_train_unnorm, y_val_unnorm = train_test_split(X_subset_normalized, y, test_size=0.2, random_state=42)

# Initialize theta for the normalized subset features
theta_initial_subset_normalized = np.zeros(X_train_subset_normalized.shape[1])

print("Shape of normalized X_subset:", X_subset_normalized.shape)
print("Shape of y (original):", y.shape)
print("Shape of X_train_subset_normalized:", X_train_subset_normalized.shape)
print("Shape of y_train_unnorm:", y_train_unnorm.shape)
print("Initial Theta for normalized subset features:", theta_initial_subset_normalized)

"""### Training with Normalized Subset Data (Target Unnormalized)

Now, we'll train the model using the min-max normalized subset of features and the original unnormalized target variable.
"""

# Define a suitable learning rate for normalized data
alpha_subset_normalized = 0.01 # Can use a typical learning rate
iterations_subset_normalized = 2000 # Same number of iterations

# Train the model with normalized subset features and unnormalized target
theta_trained_subset_normalized, training_losses_subset_normalized_history = gradient_descent(X_train_subset_normalized, y_train_unnorm, theta_initial_subset_normalized, alpha_subset_normalized, iterations_subset_normalized)

# Calculate the final validation cost with normalized subset data and unnormalized target
validation_loss_subset_normalized = compute_cost(X_val_subset_normalized, y_val_unnorm, theta_trained_subset_normalized)

print(f"Final Training Loss (Normalized Subset Features, Unnorm. Target): {training_losses_subset_normalized_history[-1]:.4f}")
print(f"Final Validation Loss (Normalized Subset Features, Unnorm. Target): {validation_loss_subset_normalized:.4f}")

"""### Training and Validation Loss Plot (Normalized Subset Data, Target Unnormalized)

Here's the plot for the normalized subset features with the original target variable.
"""

plt.figure(figsize=(12, 6))

# Plot training loss for normalized subset data
plt.plot(range(iterations_subset_normalized), training_losses_subset_normalized_history, label=f'Training Loss (Normalized Subset, LR={alpha_subset_normalized:.4f})', color='blue')

# Plot validation loss
plt.axhline(y=validation_loss_subset_normalized, color='red', linestyle='--', label=f'Validation Loss (Normalized Subset, LR={alpha_subset_normalized:.4f}) = {validation_loss_subset_normalized:.4f}')

plt.title('Training and Validation Loss over Iterations (Normalized Subset Features, Unnorm. Target)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### Data Normalization for All Features (Target Unnormalized)

Now, let's apply Min-Max Normalization to *all* features (`X_all`) while keeping the target variable `y` in its original scale.
"""

from sklearn.preprocessing import MinMaxScaler

# Initialize MinMaxScaler for all features (X_all)
scaler_X_all_norm = MinMaxScaler()
X_all_normalized = scaler_X_all_norm.fit_transform(X_all)

# Split the normalized all-feature data and original y into training and validation sets
X_train_all_normalized, X_val_all_normalized, y_train_unnorm_all, y_val_unnorm_all = train_test_split(X_all_normalized, y, test_size=0.2, random_state=42)

# Initialize theta for the normalized all features
theta_initial_all_normalized = np.zeros(X_train_all_normalized.shape[1])

print("Shape of normalized X_all:", X_all_normalized.shape)
print("Shape of y (original):", y.shape)
print("Shape of X_train_all_normalized:", X_train_all_normalized.shape)
print("Shape of y_train_unnorm_all:", y_train_unnorm_all.shape)
print("Initial Theta for normalized all features:", theta_initial_all_normalized)

"""### Training with Normalized All Features Data (Target Unnormalized)

Training the model with min-max normalized all features and the original unnormalized target variable.
"""

# Define a suitable learning rate for normalized data
alpha_all_normalized = 0.01 # Can use a typical learning rate
iterations_all_normalized = 2000 # Same number of iterations

# Train the model with normalized all features and unnormalized target
theta_trained_all_normalized, training_losses_all_normalized_history = gradient_descent(X_train_all_normalized, y_train_unnorm_all, theta_initial_all_normalized, alpha_all_normalized, iterations_all_normalized)

# Calculate the final validation cost with normalized all-feature data and unnormalized target
validation_loss_all_normalized = compute_cost(X_val_all_normalized, y_val_unnorm_all, theta_trained_all_normalized)

print(f"Final Training Loss (Normalized All Features, Unnorm. Target): {training_losses_all_normalized_history[-1]:.4f}")
print(f"Final Validation Loss (Normalized All Features, Unnorm. Target): {validation_loss_all_normalized:.4f}")

"""### Training and Validation Loss Plot (Normalized All Features, Target Unnormalized)

Finally, the plot for normalized all features with the original target variable.
"""

plt.figure(figsize=(12, 6))

# Plot training loss for normalized all features data
plt.plot(range(iterations_all_normalized), training_losses_all_normalized_history, label=f'Training Loss (Normalized All Features, LR={alpha_all_normalized:.4f})', color='blue')

# Plot validation loss
plt.axhline(y=validation_loss_all_normalized, color='red', linestyle='--', label=f'Validation Loss (Normalized All Features, LR={alpha_all_normalized:.4f}) = {validation_loss_all_normalized:.4f}')

plt.title('Training and Validation Loss over Iterations (Normalized All Features, Unnorm. Target)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### Standardized Subset Features with Unnormalized Target

Let's train a model using the previously computed standardized subset of features (`X_subset_scaled`) but with the original, unnormalized target variable (`y`).
"""

# X_subset_scaled is already computed from cell 66b5caf9

# Split the standardized subset data and original y into training and validation sets
X_train_subset_std_unnorm, X_val_subset_std_unnorm, y_train_unnorm_std_subset, y_val_unnorm_std_subset = train_test_split(X_subset_scaled, y, test_size=0.2, random_state=42)

# Initialize theta for the standardized subset features
theta_initial_subset_std_unnorm = np.zeros(X_train_subset_std_unnorm.shape[1])

print("Shape of standardized X_subset:", X_subset_scaled.shape)
print("Shape of y (original):", y.shape)
print("Shape of X_train_subset_std_unnorm:", X_train_subset_std_unnorm.shape)
print("Shape of y_train_unnorm_std_subset:", y_train_unnorm_std_subset.shape)
print("Initial Theta for standardized subset features (Unnorm. Target):", theta_initial_subset_std_unnorm)

"""#### Training with Standardized Subset Data and Unnormalized Target

Now, we'll train the model for this scenario. We'll use a reduced learning rate for better convergence, given the unnormalized target.
"""

# Define a suitable learning rate for standardized features with unnormalized target
alpha_subset_std_unnorm = 1e-5 # Reduced learning rate
iterations_subset_std_unnorm = 2000 # Same number of iterations

# Train the model with standardized subset features and unnormalized target
theta_trained_subset_std_unnorm, training_losses_subset_std_unnorm_history = gradient_descent(X_train_subset_std_unnorm, y_train_unnorm_std_subset, theta_initial_subset_std_unnorm, alpha_subset_std_unnorm, iterations_subset_std_unnorm)

# Calculate the final validation cost
validation_loss_subset_std_unnorm = compute_cost(X_val_subset_std_unnorm, y_val_unnorm_std_subset, theta_trained_subset_std_unnorm)

print(f"Final Training Loss (Std. Subset Features, Unnorm. Target): {training_losses_subset_std_unnorm_history[-1]:.4f}")
print(f"Final Validation Loss (Std. Subset Features, Unnorm. Target): {validation_loss_subset_std_unnorm:.4f}")

"""#### Plotting Training and Validation Loss (Standardized Subset Features, Unnormalized Target)"""

plt.figure(figsize=(12, 6))

# Plot training loss
plt.plot(range(iterations_subset_std_unnorm), training_losses_subset_std_unnorm_history, label=f'Training Loss (Std. Subset, LR={alpha_subset_std_unnorm:.4f})', color='blue')

# Plot validation loss
plt.axhline(y=validation_loss_subset_std_unnorm, color='red', linestyle='--', label=f'Validation Loss (Std. Subset, LR={alpha_subset_std_unnorm:.4f}) = {validation_loss_subset_std_unnorm:.4f}')

plt.title('Training and Validation Loss over Iterations (Standardized Subset Features, Unnorm. Target)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### Standardized All Features with Unnormalized Target

Next, let's analyze the model's performance when all features are standardized (`X_all_scaled`), but the target variable (`y`) remains unnormalized.
"""

# Split the standardized all-feature data and original y into training and validation sets
X_train_all_std_unnorm, X_val_all_std_unnorm, y_train_unnorm_std_all, y_val_unnorm_std_all = train_test_split(X_all_scaled, y, test_size=0.2, random_state=42)

# Initialize theta for the standardized all features
theta_initial_all_std_unnorm = np.zeros(X_train_all_std_unnorm.shape[1])

print("Shape of standardized X_all:", X_all_scaled.shape)
print("Shape of y (original):", y.shape)
print("Shape of X_train_all_std_unnorm:", X_train_all_std_unnorm.shape)
print("Shape of y_train_unnorm_std_all:", y_train_unnorm_std_all.shape)
print("Initial Theta for standardized all features (Unnorm. Target):", theta_initial_all_std_unnorm)

"""#### Training with Standardized All Features Data and Unnormalized Target

Training the model for this configuration, again with a reduced learning rate.
"""

# Define a suitable learning rate for standardized features with unnormalized target
alpha_all_std_unnorm = 1e-5 # Reduced learning rate
iterations_all_std_unnorm = 2000 # Same number of iterations

# Train the model with standardized all features and unnormalized target
theta_trained_all_std_unnorm, training_losses_all_std_unnorm_history = gradient_descent(X_train_all_std_unnorm, y_train_unnorm_std_all, theta_initial_all_std_unnorm, alpha_all_std_unnorm, iterations_all_std_unnorm)

# Calculate the final validation cost
validation_loss_all_std_unnorm = compute_cost(X_val_all_std_unnorm, y_val_unnorm_std_all, theta_trained_all_std_unnorm)

print(f"Final Training Loss (Std. All Features, Unnorm. Target): {training_losses_all_std_unnorm_history[-1]:.4f}")
print(f"Final Validation Loss (Std. All Features, Unnorm. Target): {validation_loss_all_std_unnorm:.4f}")

"""#### Plotting Training and Validation Loss (Standardized All Features, Unnormalized Target)"""

plt.figure(figsize=(12, 6))

# Plot training loss
plt.plot(range(iterations_all_std_unnorm), training_losses_all_std_unnorm_history, label=f'Training Loss (Std. All Features, LR={alpha_all_std_unnorm:.4f})', color='blue')

# Plot validation loss
plt.axhline(y=validation_loss_all_std_unnorm, color='red', linestyle='--', label=f'Validation Loss (Std. All Features, LR={alpha_all_std_unnorm:.4f}) = {validation_loss_all_std_unnorm:.4f}')

plt.title('Training and Validation Loss over Iterations (Standardized All Features, Unnorm. Target)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### L2 Regularization (Ridge Regression)

Regularization is a technique used to prevent overfitting in machine learning models by adding a penalty to the loss function. L2 regularization, also known as Ridge Regression, adds a penalty proportional to the square of the magnitude of the coefficients (`theta` values).

The modified cost function for L2 regularization is:

$$ J(\theta) = \frac{1}{2m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)})^2 + \frac{\lambda}{2m} \sum_{j=1}^{n} \theta_j^2 $$

Where:
- $h_\theta(x^{(i)})$ is the predicted value for the $i$-th example.
- $y^{(i)}$ is the actual value for the $i$-th example.
- $m$ is the number of training examples.
- $\lambda$ (lambda) is the regularization parameter, controlling the strength of the penalty.
- $\theta_j$ are the model parameters (coefficients), excluding the intercept ($\theta_0$).

A larger $\lambda$ value increases the penalty, forcing the coefficients to be smaller and reducing the model's complexity. A smaller $\lambda$ reduces the penalty, making the model more flexible. The choice of $\lambda$ is crucial and often determined through cross-validation.

For the following experiments, we will use a `lambda_param` of `0.1`.
"""

# Define the regularization parameter
lambda_param = 0.1

print(f"Using regularization parameter (lambda): {lambda_param}")

"""### Standardized Subset Features with Unnormalized Target (with L2 Regularization)

Let's re-train the model with standardized subset features and an unnormalized target, now including L2 regularization.
"""

# Reuse existing variables for standardized subset features and unnormalized target
# X_train_subset_std_unnorm, X_val_subset_std_unnorm, y_train_unnorm_std_subset, y_val_unnorm_std_subset
# Reuse alpha_subset_std_unnorm = 1e-5

# Train the model with L2 regularization
theta_trained_subset_std_unnorm_reg, training_losses_subset_std_unnorm_history_reg = gradient_descent(
    X_train_subset_std_unnorm, y_train_unnorm_std_subset, theta_initial_subset_std_unnorm,
    alpha_subset_std_unnorm, iterations_subset_std_unnorm, lambda_param=lambda_param
)

# Calculate the final validation cost with L2 regularization
validation_loss_subset_std_unnorm_reg = compute_cost(
    X_val_subset_std_unnorm, y_val_unnorm_std_subset, theta_trained_subset_std_unnorm_reg, lambda_param=lambda_param
)

print(f"Final Training Loss (Std. Subset Features, Unnorm. Target, with Reg.): {training_losses_subset_std_unnorm_history_reg[-1]:.4f}")
print(f"Final Validation Loss (Std. Subset Features, Unnorm. Target, with Reg.): {validation_loss_subset_std_unnorm_reg:.4f}")

plt.figure(figsize=(12, 6))

# Plot training loss
plt.plot(range(iterations_subset_std_unnorm), training_losses_subset_std_unnorm_history_reg, label=f'Training Loss (Std. Subset, Reg. $\lambda$={lambda_param})', color='blue')

# Plot validation loss
plt.axhline(y=validation_loss_subset_std_unnorm_reg, color='red', linestyle='--', label=f'Validation Loss (Std. Subset, Reg. $\lambda$={lambda_param}) = {validation_loss_subset_std_unnorm_reg:.4f}')

plt.title('Training and Validation Loss over Iterations (Standardized Subset Features, Unnorm. Target, with L2 Reg.)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### Standardized All Features with Unnormalized Target (with L2 Regularization)

Now, let's apply L2 regularization to the model trained with standardized all features and an unnormalized target.
"""

# Reuse existing variables for standardized all features and unnormalized target
# X_train_all_std_unnorm, X_val_all_std_unnorm, y_train_unnorm_std_all, y_val_unnorm_std_all
# Reuse alpha_all_std_unnorm = 1e-5

# Train the model with L2 regularization
theta_trained_all_std_unnorm_reg, training_losses_all_std_unnorm_history_reg = gradient_descent(
    X_train_all_std_unnorm, y_train_unnorm_std_all, theta_initial_all_std_unnorm,
    alpha_all_std_unnorm, iterations_all_std_unnorm, lambda_param=lambda_param
)

# Calculate the final validation cost with L2 regularization
validation_loss_all_std_unnorm_reg = compute_cost(
    X_val_all_std_unnorm, y_val_unnorm_std_all, theta_trained_all_std_unnorm_reg, lambda_param=lambda_param
)

print(f"Final Training Loss (Std. All Features, Unnorm. Target, with Reg.): {training_losses_all_std_unnorm_history_reg[-1]:.4f}")
print(f"Final Validation Loss (Std. All Features, Unnorm. Target, with Reg.): {validation_loss_all_std_unnorm_reg:.4f}")

plt.figure(figsize=(12, 6))

# Plot training loss
plt.plot(range(iterations_all_std_unnorm), training_losses_all_std_unnorm_history_reg, label=f'Training Loss (Std. All, Reg. $\lambda$={lambda_param})', color='blue')

# Plot validation loss
plt.axhline(y=validation_loss_all_std_unnorm_reg, color='red', linestyle='--', label=f'Validation Loss (Std. All, Reg. $\lambda$={lambda_param}) = {validation_loss_all_std_unnorm_reg:.4f}')

plt.title('Training and Validation Loss over Iterations (Standardized All Features, Unnorm. Target, with L2 Reg.)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### Normalized Subset Features with Unnormalized Target (with L2 Regularization)

Let's train the model with min-max normalized subset features and an unnormalized target, applying L2 regularization.
"""

# Reuse existing variables for normalized subset features and unnormalized target
# X_train_subset_normalized, X_val_subset_normalized, y_train_unnorm, y_val_unnorm
# Reuse alpha_subset_normalized = 0.01

# Train the model with L2 regularization
theta_trained_subset_normalized_reg, training_losses_subset_normalized_history_reg = gradient_descent(
    X_train_subset_normalized, y_train_unnorm, theta_initial_subset_normalized,
    alpha_subset_normalized, iterations_subset_normalized, lambda_param=lambda_param
)

# Calculate the final validation cost with L2 regularization
validation_loss_subset_normalized_reg = compute_cost(
    X_val_subset_normalized, y_val_unnorm, theta_trained_subset_normalized_reg, lambda_param=lambda_param
)

print(f"Final Training Loss (Normalized Subset Features, Unnorm. Target, with Reg.): {training_losses_subset_normalized_history_reg[-1]:.4f}")
print(f"Final Validation Loss (Normalized Subset Features, Unnorm. Target, with Reg.): {validation_loss_subset_normalized_reg:.4f}")

plt.figure(figsize=(12, 6))

# Plot training loss
plt.plot(range(iterations_subset_normalized), training_losses_subset_normalized_history_reg, label=f'Training Loss (Norm. Subset, Reg. $\lambda$={lambda_param})', color='blue')

# Plot validation loss
plt.axhline(y=validation_loss_subset_normalized_reg, color='red', linestyle='--', label=f'Validation Loss (Norm. Subset, Reg. $\lambda$={lambda_param}) = {validation_loss_subset_normalized_reg:.4f}')

plt.title('Training and Validation Loss over Iterations (Normalized Subset Features, Unnorm. Target, with L2 Reg.)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### Normalized All Features with Unnormalized Target (with L2 Regularization)

Finally, let's train the model with min-max normalized all features and an unnormalized target, applying L2 regularization.
"""

# Reuse existing variables for normalized all features and unnormalized target
# X_train_all_normalized, X_val_all_normalized, y_train_unnorm_all, y_val_unnorm_all
# Reuse alpha_all_normalized = 0.01

# Train the model with L2 regularization
theta_trained_all_normalized_reg, training_losses_all_normalized_history_reg = gradient_descent(
    X_train_all_normalized, y_train_unnorm_all, theta_initial_all_normalized,
    alpha_all_normalized, iterations_all_normalized, lambda_param=lambda_param
)

# Calculate the final validation cost with L2 regularization
validation_loss_all_normalized_reg = compute_cost(
    X_val_all_normalized, y_val_unnorm_all, theta_trained_all_normalized_reg, lambda_param=lambda_param
)

print(f"Final Training Loss (Normalized All Features, Unnorm. Target, with Reg.): {training_losses_all_normalized_history_reg[-1]:.4f}")
print(f"Final Validation Loss (Normalized All Features, Unnorm. Target, with Reg.): {validation_loss_all_normalized_reg:.4f}")

plt.figure(figsize=(12, 6))

# Plot training loss
plt.plot(range(iterations_all_normalized), training_losses_all_normalized_history_reg, label=f'Training Loss (Norm. All, Reg. $\lambda$={lambda_param})', color='blue')

# Plot validation loss
plt.axhline(y=validation_loss_all_normalized_reg, color='red', linestyle='--', label=f'Validation Loss (Norm. All, Reg. $\lambda$={lambda_param}) = {validation_loss_all_normalized_reg:.4f}')

plt.title('Training and Validation Loss over Iterations (Normalized All Features, Unnorm. Target, with L2 Reg.)')
plt.xlabel('Iterations')
plt.ylabel('Cost (MSE)')
plt.legend()
plt.grid(True)
plt.show()